version: "3.8"

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.7.1
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9200 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: unless-stopped

  kibana:
    image: docker.elastic.co/kibana/kibana:8.7.1
    container_name: kibana
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    depends_on:
      - elasticsearch
    restart: unless-stopped

  db_connector:
    build: ./db_script
    container_name: db_connector
    depends_on:
      elasticsearch:
        condition: service_healthy
    environment:
      - DB_HOST=10.33.1.114
      - DB_NAME=eproctjto_prod_1grau
      - DB_USER=eprocv2teste
      - DB_PASSWORD=T3st4nd@3309x
      - DB_PORT=3307
      - ES_HOST=http://elasticsearch:9200
    restart: unless-stopped

  streamlit_app:
    build: ./app
    container_name: streamlit_app
    ports:
      - "8501:8501"
    depends_on:
      db_connector:
        condition: service_started
    environment:
      - ES_HOST=http://elasticsearch:9200
    restart: unless-stopped

volumes:
  elasticsearch_data:
    driver: local
